In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub

/kaggle/input/datasets/mariumfaheem666/spam-sms-classification-using-nlp/Spam_SMS.csv

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

In [3]:
pd.set_option('display.max_colwidth', None)

In [4]:
df = pd.read_csv('/kaggle/input/datasets/mariumfaheem666/spam-sms-classification-using-nlp/Spam_SMS.csv')
df.head()

,Class,Message
0,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives around here though"

In [5]:
df.describe()

       Class                 Message
count   5574                    5574
unique     2                    5159
top      ham  Sorry, I'll call later
freq    4827                      30

## Count Vectorizer, Naive Bayes

In [6]:
cv = CountVectorizer(stop_words='english', ngram_range=(1,2),min_df = .005)
dtm = cv.fit_transform(df.Message)
dtm_df = pd.DataFrame(dtm.toarray(), columns = cv.get_feature_names_out())
dtm_df

,10,100,1000,150p,150ppm,16,18,1st,2nd,50,...,working,world,www,xxx,ya,yeah,year,yes,yo,yup
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5569,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5572,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5573,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
y = df.Class
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5569    spam
5570     ham
5571     ham
5572     ham
5573     ham
Name: Class, Length: 5574, dtype: object

In [8]:
# train/test split
X_train, X_test, y_train, y_test = train_test_split(dtm_df, y, test_size=0.2, random_state=42)

# model
model_nb = MultinomialNB()
model_nb.fit(X_train, y_train)

# predict
y_pred_nb = model_nb.predict(X_test)

# evaluate
print(classification_report(y_test, y_pred_nb))
print("Accuracy:", accuracy_score(y_test, y_pred_nb))

              precision    recall  f1-score   support

         ham       0.99      0.98      0.98       954
        spam       0.90      0.91      0.90       161

    accuracy                           0.97      1115
   macro avg       0.94      0.95      0.94      1115
weighted avg       0.97      0.97      0.97      1115

Accuracy: 0.9721973094170404

## TF/IDF, Logistic Regression

In [9]:
tv = TfidfVectorizer(stop_words = 'english', ngram_range=(1,2), min_df = .007)
xtv = tv.fit_transform(df.Message)
xtv_df = pd.DataFrame(xtv.toarray(), columns = tv.get_feature_names_out())
xtv_df

,100,1000,150p,16,18,50,500,amp,ask,babe,...,win,wish,won,work,www,ya,yeah,year,yes,yup
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.576392,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.454222,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5571,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5572,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5573,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
# train/test split
Xf_train, Xf_test, yf_train, yf_test = train_test_split(xtv_df, y, test_size=0.25, random_state=42)

# model
model_lr = LogisticRegression()
model_lr.fit(Xf_train, yf_train)

# predict
y_pred_lr = model_lr.predict(Xf_test)

# evaluate
print(classification_report(yf_test, y_pred_lr))
print("Accuracy:", accuracy_score(yf_test, y_pred_lr))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98      1203
        spam       0.98      0.81      0.89       191

    accuracy                           0.97      1394
   macro avg       0.98      0.90      0.94      1394
weighted avg       0.97      0.97      0.97      1394

Accuracy: 0.9720229555236729